[build]
  publish = "_site"
  command = "eleventy"

[[redirects]]
  from = "https://mystifying-bell-12430d.netlify.com/*"
  to = "https://www.digitalmisfit.uk/:splat"
  status = 301
  force = true
